DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
  ID          BIGINT      NOT NULL AUTO_INCREMENT  COMMENT 'auto increment id',
  HOST_NAME   VARCHAR(64) NOT NULL  COMMENT 'host name',
  PORT        VARCHAR(64) NOT NULL  COMMENT 'port',
  TYPE        INT         NOT NULL  COMMENT 'node type: ACTUAL or CONTAINER',
  LAUNCH_DATE DATE        NOT NULL  COMMENT 'launch date',
  MODIFIED    TIMESTAMP   NOT NULL  COMMENT 'modified time',
  CREATED     TIMESTAMP   NOT NULL  COMMENT 'created time',
  BIZ_TAG     VARCHAR(30 )  COMMENT '业务标识',
  STEP        INT  NOT NULL COMMENT '流水号步长',
  MIN_SEQ     VARCHAR(30 ) NOT NULL COMMENT '最小流水号信息',
  MIDDLE_ID   VARCHAR(30 ) NOT NULL COMMENT '阈值',
  MAX_SEQ     VARCHAR(30 ) NOT NULL COMMENT '最大流水号信息',
  CURR_SEQ    VARCHAR(30 ) NOT NULL COMMENT '当前流水号值',
  COUNT_SEQ   VARCHAR(30) NOT NULL COMMENT '流水号累计次数',
  PRIMARY KEY (ID)
)
  COMMENT ='DB WorkerID Assigner for UID Generator', ENGINE = INNODB;

#//HOST_NAME和BIZ_TAG是唯一约束条件，映射为ID