package yunyun.entity;

import java.math.BigDecimal;

public class CifClientPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_key
     *
     * @mbggenerated
     */
    private Long clientKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_no
     *
     * @mbggenerated
     */
    private String clientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_type
     *
     * @mbggenerated
     */
    private String clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.category_type
     *
     * @mbggenerated
     */
    private String categoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_grp
     *
     * @mbggenerated
     */
    private String clientGrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_short
     *
     * @mbggenerated
     */
    private String clientShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.ch_client_name
     *
     * @mbggenerated
     */
    private String chClientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_name
     *
     * @mbggenerated
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.name_suffix
     *
     * @mbggenerated
     */
    private String nameSuffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_mnemonic
     *
     * @mbggenerated
     */
    private String clientMnemonic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_alias
     *
     * @mbggenerated
     */
    private String clientAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.acct_exec
     *
     * @mbggenerated
     */
    private String acctExec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.country_loc
     *
     * @mbggenerated
     */
    private String countryLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.state_loc
     *
     * @mbggenerated
     */
    private String stateLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_city
     *
     * @mbggenerated
     */
    private String clientCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.country_citizen
     *
     * @mbggenerated
     */
    private String countryCitizen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.country_risk
     *
     * @mbggenerated
     */
    private String countryRisk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.ctrl_branch
     *
     * @mbggenerated
     */
    private String ctrlBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.profit_centre
     *
     * @mbggenerated
     */
    private String profitCentre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_1
     *
     * @mbggenerated
     */
    private String class1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_2
     *
     * @mbggenerated
     */
    private String class2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_3
     *
     * @mbggenerated
     */
    private String class3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_4
     *
     * @mbggenerated
     */
    private String class4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_5
     *
     * @mbggenerated
     */
    private String class5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.narrative
     *
     * @mbggenerated
     */
    private String narrative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.internal_ind
     *
     * @mbggenerated
     */
    private String internalInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.taxable_ind
     *
     * @mbggenerated
     */
    private String taxableInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_spread
     *
     * @mbggenerated
     */
    private BigDecimal clientSpread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.risk_weight
     *
     * @mbggenerated
     */
    private BigDecimal riskWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.status_info
     *
     * @mbggenerated
     */
    private String statusInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_status
     *
     * @mbggenerated
     */
    private String clientStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tran_status
     *
     * @mbggenerated
     */
    private String tranStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.closed_date
     *
     * @mbggenerated
     */
    private String closedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.client_indicator
     *
     * @mbggenerated
     */
    private String clientIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.postal_code
     *
     * @mbggenerated
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.control_dept
     *
     * @mbggenerated
     */
    private String controlDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.source_type
     *
     * @mbggenerated
     */
    private String sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.written_language
     *
     * @mbggenerated
     */
    private String writtenLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.spoken_language
     *
     * @mbggenerated
     */
    private String spokenLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.print_language
     *
     * @mbggenerated
     */
    private String printLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.inland_offshore
     *
     * @mbggenerated
     */
    private String inlandOffshore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.temp_client
     *
     * @mbggenerated
     */
    private String tempClient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.pep_ind
     *
     * @mbggenerated
     */
    private String pepInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.info_lack
     *
     * @mbggenerated
     */
    private String infoLack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_level
     *
     * @mbggenerated
     */
    private String classLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.class_level_date
     *
     * @mbggenerated
     */
    private String classLevelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.old_client_no
     *
     * @mbggenerated
     */
    private String oldClientNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.creation_user_id
     *
     * @mbggenerated
     */
    private String creationUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.creation_date
     *
     * @mbggenerated
     */
    private String creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.last_change_user_id
     *
     * @mbggenerated
     */
    private String lastChangeUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.last_change_date
     *
     * @mbggenerated
     */
    private String lastChangeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.blacklist_ind
     *
     * @mbggenerated
     */
    private String blacklistInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.business
     *
     * @mbggenerated
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.cr_rating
     *
     * @mbggenerated
     */
    private String crRating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.voucher_type
     *
     * @mbggenerated
     */
    private String voucherType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.taxpayer_type
     *
     * @mbggenerated
     */
    private String taxpayerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.is_formal
     *
     * @mbggenerated
     */
    private String isFormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tran_timestamp
     *
     * @mbggenerated
     */
    private String tranTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tran_time
     *
     * @mbggenerated
     */
    private Long tranTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.router_key
     *
     * @mbggenerated
     */
    private String routerKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tax_org_type
     *
     * @mbggenerated
     */
    private String taxOrgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tax_flag
     *
     * @mbggenerated
     */
    private String taxFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tax_country
     *
     * @mbggenerated
     */
    private String taxCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.taxpayer_id
     *
     * @mbggenerated
     */
    private String taxpayerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.unprovide_id_reason
     *
     * @mbggenerated
     */
    private String unprovideIdReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.tax_remark
     *
     * @mbggenerated
     */
    private String taxRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.CLIENT_INTEGRAL
     *
     * @mbggenerated
     */
    private String clientIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_client.CONTRIBUTION
     *
     * @mbggenerated
     */
    private String contribution;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_key
     *
     * @return the value of cif_client.client_key
     *
     * @mbggenerated
     */
    public Long getClientKey() {
        return clientKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_key
     *
     * @param clientKey the value for cif_client.client_key
     *
     * @mbggenerated
     */
    public void setClientKey(Long clientKey) {
        this.clientKey = clientKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_no
     *
     * @return the value of cif_client.client_no
     *
     * @mbggenerated
     */
    public String getClientNo() {
        return clientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_no
     *
     * @param clientNo the value for cif_client.client_no
     *
     * @mbggenerated
     */
    public void setClientNo(String clientNo) {
        this.clientNo = clientNo == null ? null : clientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_type
     *
     * @return the value of cif_client.client_type
     *
     * @mbggenerated
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_type
     *
     * @param clientType the value for cif_client.client_type
     *
     * @mbggenerated
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.category_type
     *
     * @return the value of cif_client.category_type
     *
     * @mbggenerated
     */
    public String getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.category_type
     *
     * @param categoryType the value for cif_client.category_type
     *
     * @mbggenerated
     */
    public void setCategoryType(String categoryType) {
        this.categoryType = categoryType == null ? null : categoryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_grp
     *
     * @return the value of cif_client.client_grp
     *
     * @mbggenerated
     */
    public String getClientGrp() {
        return clientGrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_grp
     *
     * @param clientGrp the value for cif_client.client_grp
     *
     * @mbggenerated
     */
    public void setClientGrp(String clientGrp) {
        this.clientGrp = clientGrp == null ? null : clientGrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_short
     *
     * @return the value of cif_client.client_short
     *
     * @mbggenerated
     */
    public String getClientShort() {
        return clientShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_short
     *
     * @param clientShort the value for cif_client.client_short
     *
     * @mbggenerated
     */
    public void setClientShort(String clientShort) {
        this.clientShort = clientShort == null ? null : clientShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.ch_client_name
     *
     * @return the value of cif_client.ch_client_name
     *
     * @mbggenerated
     */
    public String getChClientName() {
        return chClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.ch_client_name
     *
     * @param chClientName the value for cif_client.ch_client_name
     *
     * @mbggenerated
     */
    public void setChClientName(String chClientName) {
        this.chClientName = chClientName == null ? null : chClientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_name
     *
     * @return the value of cif_client.client_name
     *
     * @mbggenerated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_name
     *
     * @param clientName the value for cif_client.client_name
     *
     * @mbggenerated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.name_suffix
     *
     * @return the value of cif_client.name_suffix
     *
     * @mbggenerated
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.name_suffix
     *
     * @param nameSuffix the value for cif_client.name_suffix
     *
     * @mbggenerated
     */
    public void setNameSuffix(String nameSuffix) {
        this.nameSuffix = nameSuffix == null ? null : nameSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_mnemonic
     *
     * @return the value of cif_client.client_mnemonic
     *
     * @mbggenerated
     */
    public String getClientMnemonic() {
        return clientMnemonic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_mnemonic
     *
     * @param clientMnemonic the value for cif_client.client_mnemonic
     *
     * @mbggenerated
     */
    public void setClientMnemonic(String clientMnemonic) {
        this.clientMnemonic = clientMnemonic == null ? null : clientMnemonic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_alias
     *
     * @return the value of cif_client.client_alias
     *
     * @mbggenerated
     */
    public String getClientAlias() {
        return clientAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_alias
     *
     * @param clientAlias the value for cif_client.client_alias
     *
     * @mbggenerated
     */
    public void setClientAlias(String clientAlias) {
        this.clientAlias = clientAlias == null ? null : clientAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.address
     *
     * @return the value of cif_client.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.address
     *
     * @param address the value for cif_client.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.acct_exec
     *
     * @return the value of cif_client.acct_exec
     *
     * @mbggenerated
     */
    public String getAcctExec() {
        return acctExec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.acct_exec
     *
     * @param acctExec the value for cif_client.acct_exec
     *
     * @mbggenerated
     */
    public void setAcctExec(String acctExec) {
        this.acctExec = acctExec == null ? null : acctExec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.country_loc
     *
     * @return the value of cif_client.country_loc
     *
     * @mbggenerated
     */
    public String getCountryLoc() {
        return countryLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.country_loc
     *
     * @param countryLoc the value for cif_client.country_loc
     *
     * @mbggenerated
     */
    public void setCountryLoc(String countryLoc) {
        this.countryLoc = countryLoc == null ? null : countryLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.state_loc
     *
     * @return the value of cif_client.state_loc
     *
     * @mbggenerated
     */
    public String getStateLoc() {
        return stateLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.state_loc
     *
     * @param stateLoc the value for cif_client.state_loc
     *
     * @mbggenerated
     */
    public void setStateLoc(String stateLoc) {
        this.stateLoc = stateLoc == null ? null : stateLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_city
     *
     * @return the value of cif_client.client_city
     *
     * @mbggenerated
     */
    public String getClientCity() {
        return clientCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_city
     *
     * @param clientCity the value for cif_client.client_city
     *
     * @mbggenerated
     */
    public void setClientCity(String clientCity) {
        this.clientCity = clientCity == null ? null : clientCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.country_citizen
     *
     * @return the value of cif_client.country_citizen
     *
     * @mbggenerated
     */
    public String getCountryCitizen() {
        return countryCitizen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.country_citizen
     *
     * @param countryCitizen the value for cif_client.country_citizen
     *
     * @mbggenerated
     */
    public void setCountryCitizen(String countryCitizen) {
        this.countryCitizen = countryCitizen == null ? null : countryCitizen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.country_risk
     *
     * @return the value of cif_client.country_risk
     *
     * @mbggenerated
     */
    public String getCountryRisk() {
        return countryRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.country_risk
     *
     * @param countryRisk the value for cif_client.country_risk
     *
     * @mbggenerated
     */
    public void setCountryRisk(String countryRisk) {
        this.countryRisk = countryRisk == null ? null : countryRisk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.ctrl_branch
     *
     * @return the value of cif_client.ctrl_branch
     *
     * @mbggenerated
     */
    public String getCtrlBranch() {
        return ctrlBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.ctrl_branch
     *
     * @param ctrlBranch the value for cif_client.ctrl_branch
     *
     * @mbggenerated
     */
    public void setCtrlBranch(String ctrlBranch) {
        this.ctrlBranch = ctrlBranch == null ? null : ctrlBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.profit_centre
     *
     * @return the value of cif_client.profit_centre
     *
     * @mbggenerated
     */
    public String getProfitCentre() {
        return profitCentre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.profit_centre
     *
     * @param profitCentre the value for cif_client.profit_centre
     *
     * @mbggenerated
     */
    public void setProfitCentre(String profitCentre) {
        this.profitCentre = profitCentre == null ? null : profitCentre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_1
     *
     * @return the value of cif_client.class_1
     *
     * @mbggenerated
     */
    public String getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_1
     *
     * @param class1 the value for cif_client.class_1
     *
     * @mbggenerated
     */
    public void setClass1(String class1) {
        this.class1 = class1 == null ? null : class1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_2
     *
     * @return the value of cif_client.class_2
     *
     * @mbggenerated
     */
    public String getClass2() {
        return class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_2
     *
     * @param class2 the value for cif_client.class_2
     *
     * @mbggenerated
     */
    public void setClass2(String class2) {
        this.class2 = class2 == null ? null : class2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_3
     *
     * @return the value of cif_client.class_3
     *
     * @mbggenerated
     */
    public String getClass3() {
        return class3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_3
     *
     * @param class3 the value for cif_client.class_3
     *
     * @mbggenerated
     */
    public void setClass3(String class3) {
        this.class3 = class3 == null ? null : class3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_4
     *
     * @return the value of cif_client.class_4
     *
     * @mbggenerated
     */
    public String getClass4() {
        return class4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_4
     *
     * @param class4 the value for cif_client.class_4
     *
     * @mbggenerated
     */
    public void setClass4(String class4) {
        this.class4 = class4 == null ? null : class4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_5
     *
     * @return the value of cif_client.class_5
     *
     * @mbggenerated
     */
    public String getClass5() {
        return class5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_5
     *
     * @param class5 the value for cif_client.class_5
     *
     * @mbggenerated
     */
    public void setClass5(String class5) {
        this.class5 = class5 == null ? null : class5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.narrative
     *
     * @return the value of cif_client.narrative
     *
     * @mbggenerated
     */
    public String getNarrative() {
        return narrative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.narrative
     *
     * @param narrative the value for cif_client.narrative
     *
     * @mbggenerated
     */
    public void setNarrative(String narrative) {
        this.narrative = narrative == null ? null : narrative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.internal_ind
     *
     * @return the value of cif_client.internal_ind
     *
     * @mbggenerated
     */
    public String getInternalInd() {
        return internalInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.internal_ind
     *
     * @param internalInd the value for cif_client.internal_ind
     *
     * @mbggenerated
     */
    public void setInternalInd(String internalInd) {
        this.internalInd = internalInd == null ? null : internalInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.taxable_ind
     *
     * @return the value of cif_client.taxable_ind
     *
     * @mbggenerated
     */
    public String getTaxableInd() {
        return taxableInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.taxable_ind
     *
     * @param taxableInd the value for cif_client.taxable_ind
     *
     * @mbggenerated
     */
    public void setTaxableInd(String taxableInd) {
        this.taxableInd = taxableInd == null ? null : taxableInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_spread
     *
     * @return the value of cif_client.client_spread
     *
     * @mbggenerated
     */
    public BigDecimal getClientSpread() {
        return clientSpread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_spread
     *
     * @param clientSpread the value for cif_client.client_spread
     *
     * @mbggenerated
     */
    public void setClientSpread(BigDecimal clientSpread) {
        this.clientSpread = clientSpread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.risk_weight
     *
     * @return the value of cif_client.risk_weight
     *
     * @mbggenerated
     */
    public BigDecimal getRiskWeight() {
        return riskWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.risk_weight
     *
     * @param riskWeight the value for cif_client.risk_weight
     *
     * @mbggenerated
     */
    public void setRiskWeight(BigDecimal riskWeight) {
        this.riskWeight = riskWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.status_info
     *
     * @return the value of cif_client.status_info
     *
     * @mbggenerated
     */
    public String getStatusInfo() {
        return statusInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.status_info
     *
     * @param statusInfo the value for cif_client.status_info
     *
     * @mbggenerated
     */
    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo == null ? null : statusInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_status
     *
     * @return the value of cif_client.client_status
     *
     * @mbggenerated
     */
    public String getClientStatus() {
        return clientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_status
     *
     * @param clientStatus the value for cif_client.client_status
     *
     * @mbggenerated
     */
    public void setClientStatus(String clientStatus) {
        this.clientStatus = clientStatus == null ? null : clientStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tran_status
     *
     * @return the value of cif_client.tran_status
     *
     * @mbggenerated
     */
    public String getTranStatus() {
        return tranStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tran_status
     *
     * @param tranStatus the value for cif_client.tran_status
     *
     * @mbggenerated
     */
    public void setTranStatus(String tranStatus) {
        this.tranStatus = tranStatus == null ? null : tranStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.closed_date
     *
     * @return the value of cif_client.closed_date
     *
     * @mbggenerated
     */
    public String getClosedDate() {
        return closedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.closed_date
     *
     * @param closedDate the value for cif_client.closed_date
     *
     * @mbggenerated
     */
    public void setClosedDate(String closedDate) {
        this.closedDate = closedDate == null ? null : closedDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.client_indicator
     *
     * @return the value of cif_client.client_indicator
     *
     * @mbggenerated
     */
    public String getClientIndicator() {
        return clientIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.client_indicator
     *
     * @param clientIndicator the value for cif_client.client_indicator
     *
     * @mbggenerated
     */
    public void setClientIndicator(String clientIndicator) {
        this.clientIndicator = clientIndicator == null ? null : clientIndicator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.district
     *
     * @return the value of cif_client.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.district
     *
     * @param district the value for cif_client.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.postal_code
     *
     * @return the value of cif_client.postal_code
     *
     * @mbggenerated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.postal_code
     *
     * @param postalCode the value for cif_client.postal_code
     *
     * @mbggenerated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.control_dept
     *
     * @return the value of cif_client.control_dept
     *
     * @mbggenerated
     */
    public String getControlDept() {
        return controlDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.control_dept
     *
     * @param controlDept the value for cif_client.control_dept
     *
     * @mbggenerated
     */
    public void setControlDept(String controlDept) {
        this.controlDept = controlDept == null ? null : controlDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.source_type
     *
     * @return the value of cif_client.source_type
     *
     * @mbggenerated
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.source_type
     *
     * @param sourceType the value for cif_client.source_type
     *
     * @mbggenerated
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType == null ? null : sourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.written_language
     *
     * @return the value of cif_client.written_language
     *
     * @mbggenerated
     */
    public String getWrittenLanguage() {
        return writtenLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.written_language
     *
     * @param writtenLanguage the value for cif_client.written_language
     *
     * @mbggenerated
     */
    public void setWrittenLanguage(String writtenLanguage) {
        this.writtenLanguage = writtenLanguage == null ? null : writtenLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.spoken_language
     *
     * @return the value of cif_client.spoken_language
     *
     * @mbggenerated
     */
    public String getSpokenLanguage() {
        return spokenLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.spoken_language
     *
     * @param spokenLanguage the value for cif_client.spoken_language
     *
     * @mbggenerated
     */
    public void setSpokenLanguage(String spokenLanguage) {
        this.spokenLanguage = spokenLanguage == null ? null : spokenLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.print_language
     *
     * @return the value of cif_client.print_language
     *
     * @mbggenerated
     */
    public String getPrintLanguage() {
        return printLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.print_language
     *
     * @param printLanguage the value for cif_client.print_language
     *
     * @mbggenerated
     */
    public void setPrintLanguage(String printLanguage) {
        this.printLanguage = printLanguage == null ? null : printLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.inland_offshore
     *
     * @return the value of cif_client.inland_offshore
     *
     * @mbggenerated
     */
    public String getInlandOffshore() {
        return inlandOffshore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.inland_offshore
     *
     * @param inlandOffshore the value for cif_client.inland_offshore
     *
     * @mbggenerated
     */
    public void setInlandOffshore(String inlandOffshore) {
        this.inlandOffshore = inlandOffshore == null ? null : inlandOffshore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.temp_client
     *
     * @return the value of cif_client.temp_client
     *
     * @mbggenerated
     */
    public String getTempClient() {
        return tempClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.temp_client
     *
     * @param tempClient the value for cif_client.temp_client
     *
     * @mbggenerated
     */
    public void setTempClient(String tempClient) {
        this.tempClient = tempClient == null ? null : tempClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.pep_ind
     *
     * @return the value of cif_client.pep_ind
     *
     * @mbggenerated
     */
    public String getPepInd() {
        return pepInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.pep_ind
     *
     * @param pepInd the value for cif_client.pep_ind
     *
     * @mbggenerated
     */
    public void setPepInd(String pepInd) {
        this.pepInd = pepInd == null ? null : pepInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.info_lack
     *
     * @return the value of cif_client.info_lack
     *
     * @mbggenerated
     */
    public String getInfoLack() {
        return infoLack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.info_lack
     *
     * @param infoLack the value for cif_client.info_lack
     *
     * @mbggenerated
     */
    public void setInfoLack(String infoLack) {
        this.infoLack = infoLack == null ? null : infoLack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_level
     *
     * @return the value of cif_client.class_level
     *
     * @mbggenerated
     */
    public String getClassLevel() {
        return classLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_level
     *
     * @param classLevel the value for cif_client.class_level
     *
     * @mbggenerated
     */
    public void setClassLevel(String classLevel) {
        this.classLevel = classLevel == null ? null : classLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.class_level_date
     *
     * @return the value of cif_client.class_level_date
     *
     * @mbggenerated
     */
    public String getClassLevelDate() {
        return classLevelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.class_level_date
     *
     * @param classLevelDate the value for cif_client.class_level_date
     *
     * @mbggenerated
     */
    public void setClassLevelDate(String classLevelDate) {
        this.classLevelDate = classLevelDate == null ? null : classLevelDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.old_client_no
     *
     * @return the value of cif_client.old_client_no
     *
     * @mbggenerated
     */
    public String getOldClientNo() {
        return oldClientNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.old_client_no
     *
     * @param oldClientNo the value for cif_client.old_client_no
     *
     * @mbggenerated
     */
    public void setOldClientNo(String oldClientNo) {
        this.oldClientNo = oldClientNo == null ? null : oldClientNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.creation_user_id
     *
     * @return the value of cif_client.creation_user_id
     *
     * @mbggenerated
     */
    public String getCreationUserId() {
        return creationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.creation_user_id
     *
     * @param creationUserId the value for cif_client.creation_user_id
     *
     * @mbggenerated
     */
    public void setCreationUserId(String creationUserId) {
        this.creationUserId = creationUserId == null ? null : creationUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.creation_date
     *
     * @return the value of cif_client.creation_date
     *
     * @mbggenerated
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.creation_date
     *
     * @param creationDate the value for cif_client.creation_date
     *
     * @mbggenerated
     */
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate == null ? null : creationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.last_change_user_id
     *
     * @return the value of cif_client.last_change_user_id
     *
     * @mbggenerated
     */
    public String getLastChangeUserId() {
        return lastChangeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.last_change_user_id
     *
     * @param lastChangeUserId the value for cif_client.last_change_user_id
     *
     * @mbggenerated
     */
    public void setLastChangeUserId(String lastChangeUserId) {
        this.lastChangeUserId = lastChangeUserId == null ? null : lastChangeUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.last_change_date
     *
     * @return the value of cif_client.last_change_date
     *
     * @mbggenerated
     */
    public String getLastChangeDate() {
        return lastChangeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.last_change_date
     *
     * @param lastChangeDate the value for cif_client.last_change_date
     *
     * @mbggenerated
     */
    public void setLastChangeDate(String lastChangeDate) {
        this.lastChangeDate = lastChangeDate == null ? null : lastChangeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.blacklist_ind
     *
     * @return the value of cif_client.blacklist_ind
     *
     * @mbggenerated
     */
    public String getBlacklistInd() {
        return blacklistInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.blacklist_ind
     *
     * @param blacklistInd the value for cif_client.blacklist_ind
     *
     * @mbggenerated
     */
    public void setBlacklistInd(String blacklistInd) {
        this.blacklistInd = blacklistInd == null ? null : blacklistInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.company
     *
     * @return the value of cif_client.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.company
     *
     * @param company the value for cif_client.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.industry
     *
     * @return the value of cif_client.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.industry
     *
     * @param industry the value for cif_client.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.business
     *
     * @return the value of cif_client.business
     *
     * @mbggenerated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.business
     *
     * @param business the value for cif_client.business
     *
     * @mbggenerated
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.cr_rating
     *
     * @return the value of cif_client.cr_rating
     *
     * @mbggenerated
     */
    public String getCrRating() {
        return crRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.cr_rating
     *
     * @param crRating the value for cif_client.cr_rating
     *
     * @mbggenerated
     */
    public void setCrRating(String crRating) {
        this.crRating = crRating == null ? null : crRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.voucher_type
     *
     * @return the value of cif_client.voucher_type
     *
     * @mbggenerated
     */
    public String getVoucherType() {
        return voucherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.voucher_type
     *
     * @param voucherType the value for cif_client.voucher_type
     *
     * @mbggenerated
     */
    public void setVoucherType(String voucherType) {
        this.voucherType = voucherType == null ? null : voucherType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.taxpayer_type
     *
     * @return the value of cif_client.taxpayer_type
     *
     * @mbggenerated
     */
    public String getTaxpayerType() {
        return taxpayerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.taxpayer_type
     *
     * @param taxpayerType the value for cif_client.taxpayer_type
     *
     * @mbggenerated
     */
    public void setTaxpayerType(String taxpayerType) {
        this.taxpayerType = taxpayerType == null ? null : taxpayerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.is_formal
     *
     * @return the value of cif_client.is_formal
     *
     * @mbggenerated
     */
    public String getIsFormal() {
        return isFormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.is_formal
     *
     * @param isFormal the value for cif_client.is_formal
     *
     * @mbggenerated
     */
    public void setIsFormal(String isFormal) {
        this.isFormal = isFormal == null ? null : isFormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tran_timestamp
     *
     * @return the value of cif_client.tran_timestamp
     *
     * @mbggenerated
     */
    public String getTranTimestamp() {
        return tranTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tran_timestamp
     *
     * @param tranTimestamp the value for cif_client.tran_timestamp
     *
     * @mbggenerated
     */
    public void setTranTimestamp(String tranTimestamp) {
        this.tranTimestamp = tranTimestamp == null ? null : tranTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tran_time
     *
     * @return the value of cif_client.tran_time
     *
     * @mbggenerated
     */
    public Long getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tran_time
     *
     * @param tranTime the value for cif_client.tran_time
     *
     * @mbggenerated
     */
    public void setTranTime(Long tranTime) {
        this.tranTime = tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.router_key
     *
     * @return the value of cif_client.router_key
     *
     * @mbggenerated
     */
    public String getRouterKey() {
        return routerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.router_key
     *
     * @param routerKey the value for cif_client.router_key
     *
     * @mbggenerated
     */
    public void setRouterKey(String routerKey) {
        this.routerKey = routerKey == null ? null : routerKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tax_org_type
     *
     * @return the value of cif_client.tax_org_type
     *
     * @mbggenerated
     */
    public String getTaxOrgType() {
        return taxOrgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tax_org_type
     *
     * @param taxOrgType the value for cif_client.tax_org_type
     *
     * @mbggenerated
     */
    public void setTaxOrgType(String taxOrgType) {
        this.taxOrgType = taxOrgType == null ? null : taxOrgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tax_flag
     *
     * @return the value of cif_client.tax_flag
     *
     * @mbggenerated
     */
    public String getTaxFlag() {
        return taxFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tax_flag
     *
     * @param taxFlag the value for cif_client.tax_flag
     *
     * @mbggenerated
     */
    public void setTaxFlag(String taxFlag) {
        this.taxFlag = taxFlag == null ? null : taxFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tax_country
     *
     * @return the value of cif_client.tax_country
     *
     * @mbggenerated
     */
    public String getTaxCountry() {
        return taxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tax_country
     *
     * @param taxCountry the value for cif_client.tax_country
     *
     * @mbggenerated
     */
    public void setTaxCountry(String taxCountry) {
        this.taxCountry = taxCountry == null ? null : taxCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.taxpayer_id
     *
     * @return the value of cif_client.taxpayer_id
     *
     * @mbggenerated
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.taxpayer_id
     *
     * @param taxpayerId the value for cif_client.taxpayer_id
     *
     * @mbggenerated
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId == null ? null : taxpayerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.unprovide_id_reason
     *
     * @return the value of cif_client.unprovide_id_reason
     *
     * @mbggenerated
     */
    public String getUnprovideIdReason() {
        return unprovideIdReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.unprovide_id_reason
     *
     * @param unprovideIdReason the value for cif_client.unprovide_id_reason
     *
     * @mbggenerated
     */
    public void setUnprovideIdReason(String unprovideIdReason) {
        this.unprovideIdReason = unprovideIdReason == null ? null : unprovideIdReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.tax_remark
     *
     * @return the value of cif_client.tax_remark
     *
     * @mbggenerated
     */
    public String getTaxRemark() {
        return taxRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.tax_remark
     *
     * @param taxRemark the value for cif_client.tax_remark
     *
     * @mbggenerated
     */
    public void setTaxRemark(String taxRemark) {
        this.taxRemark = taxRemark == null ? null : taxRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.CLIENT_INTEGRAL
     *
     * @return the value of cif_client.CLIENT_INTEGRAL
     *
     * @mbggenerated
     */
    public String getClientIntegral() {
        return clientIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.CLIENT_INTEGRAL
     *
     * @param clientIntegral the value for cif_client.CLIENT_INTEGRAL
     *
     * @mbggenerated
     */
    public void setClientIntegral(String clientIntegral) {
        this.clientIntegral = clientIntegral == null ? null : clientIntegral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_client.CONTRIBUTION
     *
     * @return the value of cif_client.CONTRIBUTION
     *
     * @mbggenerated
     */
    public String getContribution() {
        return contribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_client.CONTRIBUTION
     *
     * @param contribution the value for cif_client.CONTRIBUTION
     *
     * @mbggenerated
     */
    public void setContribution(String contribution) {
        this.contribution = contribution == null ? null : contribution.trim();
    }
}