DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
  ID          BIGINT      NOT NULL AUTO_INCREMENT  COMMENT 'auto increment id',
  HOST_NAME   VARCHAR(64) NOT NULL  COMMENT 'host name',
  PORT        VARCHAR(64) NOT NULL  COMMENT 'port',
  TYPE        VARCHAR(30) NOT NULL  COMMENT 'node type: ACTUAL or CONTAINER',
  LAUNCH_DATE TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT 'launch date',
  MODIFIED    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'modified time',
  CREATED     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
  BIZ_TAG     VARCHAR(30) NOT NULL DEFAULT  'def' COMMENT '业务标识',
  MIN_SEQ     BIGINT NOT NULL COMMENT '最小流水号信息',
  MAX_SEQ     BIGINT NOT NULL COMMENT '最大流水号信息',
  STEP        INT  NOT NULL COMMENT '流水号步长',
  CURR_SEQ    BIGINT NOT NULL COMMENT '当前流水号值',
  COUNT_SEQ   BIGINT NOT NULL COMMENT '流水循环次数',
  MIDDLE_ID   VARCHAR(30) NOT NULL COMMENT '阈值',
  SEQ_CYCLE   VARCHAR(30) NOT NULL DEFAULT 'Y' COMMENT '是否循环序列 Y-是；N-不是',
  SEQ_CACHE   BIGINT NOT NULL COMMENT '缓存序列数',
  CACHE_COUNT BIGINT NOT NULL COMMENT '缓存序列计数',
  PRIMARY KEY (ID),
  UNIQUE KEY `HOST_NAME` (`HOST_NAME`,`BIZ_TAG`)
)
  COMMENT ='DB WorkerID Assigner for UID Generator', ENGINE = INNODB;

 DROP TABLE IF EXISTS hibernate_sequence;
  CREATE TABLE `hibernate_sequence` (
  `next_val` bigint(20) DEFAULT NULL
) COMMENT ='DB hibernate_sequence Assigner for UID Generator', ENGINE = INNODB;


